### ISSUE TITLE
Simplify `hello-world` exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/v3-launch#46]
Each `hello-world` exercise should be simplified to the point that the student only needs to replace the text `"Goodbye, Mars!"` with the text `"Hello, World!"` There should be no parameters or anything, just the most simple way in which to return the text `"Hello, World!"`

**Comment by Stargator** [comment]
Since this touches on the larger effort of this ticket that impacts all tracks, I am including my comment from the Dart track:

> @ErikSchierboom We still want folks to **do something** that will cause the tests to pass. If we give them a completed exercise (albeit one that would seem confusing if there already is a string being returned), they won't know the pattern of exercise, make changes until tests pass, then submit solution.
> 
> We are not teaching them programming, they should already have some experience. I would say enough to know to complete the function.

**Comment by iHiD** [comment]
> We are not teaching them programming, they should already have some experience. I would say enough to know to complete the function.

I agree with this in general. But if someone is coming from a background in programming assembly, or has a maths background, they might not know how to init strings. It's easy in dart - it's just `""` but they might not know that. And equally the use of the return keyword, while obvious to you, might be less obvious to many. So while I agree that the majority of programmers coming from a similar language would work it out, I don't think it's as clearcut as you feel. 

On tracks that have concepts, many tracks have deliberately not introduced strings until later on. There can be lots of complexity in strings that don't exist in numbers (e.g. unicode, literals). When strings *are* introduced, then there's a concept exercise that teaches them. Similarly with return. So asking someone to use strings and returns before they're taught violates the principle of those tracks.

The point of `hello world` is to check they've got the environment set up and that the CLI works (and/or that they understand how to use the online editor). It's not to teach them any coding in itself. The reason we've mandated that `two-fer` comes next from tracks without concepts is that it's a similarly simple exercise but *is* expected make someone do some actual programming, at which point they can google around to find an answer to how to init strings, etc.

> they won't know the pattern of exercise, make changes until tests pass, then submit solution.

This is a really good point, but if `return "Hello, World!` is as easy as you feel then they still wouldn't need to do that. And if it's hard enough that they have to go through the testing-flow a few times, then we've made Hello World too hard to serve its purpose. Also, in the online editor, which we're anticipating most people to use for the first couple of exercises on each track, they will still have to run the tests in order to submit, so they'll get the feel of it, even if they don't see tests fail.

---

I think your objections make loads of sense, but I still think it's the right thing to do to standardise this across tracks and give people a consistent first exercise to solve. It also means we can do more interesting things in the UI, knowing that we can say "You only need to change 'Goodbye, Mars!' to 'Hello, World!'" and that that is true for all tracks. It enables us to build out tutorial content that is relevant everywhere, etc. Then once someone gets passed that first exercise the fun starts with real exercises.

**Comment by Stargator** [comment]
Okay, thanks. I do like the idea of a consistent introduction period for all tracks.

Since hello world is a practice exercise I don't think is the lies on which concept exercises exist. But I'm fine with this moving forward for the Dart track.

**Comment by ErikSchierboom** [comment]
> Since hello world is a practice exercise I don't think is the lies on which concept exercises exist. But I'm fine with this moving forward for the Dart track.

hello-world is a "special" practice exercise as each student _has_ to finish it before even being allowed to start any concept exercises. So it's probably best to consider it be neither a concept- or practice exercise :)

**Comment by iHiD** [comment]
Yeah, internally we treat it as a special type of "tutorial" exercise. Great. We'll merge the Dart when and can then close this. Thanks for the pragmatism, @Stargator 🙂
